# Site settings
title: Lindblad IT-konsultation
tag_text: Solo
description: Lindblad IT-konsultation
url: https://lindblad.info
author: Niklas Lindblad
author_google_url: https://plus.google.com/u/1/+NiklasLindblad
# Build settings
markdown: kramdown
exclude: ["README.md", "_nginx"]
sass:
  style: compressed
